name: search_party_rabbitmq
services:  
  rabbit:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmqhost    
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"